/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GerenciaEmp;

import GerenciaEmp.Classes.Contratado;
import GerenciaEmp.Classes.Funcionario;
import GerenciaEmp.Classes.Gerente;
import GerenciaEmp.Classes.Terceirizado;
import static GerenciaEmp.MenuPrincipal.funcionario;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Toni
 */
public class CadastroContratado extends javax.swing.JFrame {


    /**
     * Creates new form CadastroContratado
     */
    Funcionario p;
    public CadastroContratado() {
        initComponents();
       
       
      
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        TF_Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TF_Cod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TF_Email = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        JB_Pesquisar = new javax.swing.JButton();
        JB_Excluir = new javax.swing.JButton();
        JB_Alterar = new javax.swing.JButton();
        JB_Cancelar = new javax.swing.JButton();
        JB_Imprimir = new javax.swing.JButton();
        JP_C = new javax.swing.JPanel();
        CB_D_A = new javax.swing.JComboBox();
        CB_D_D = new javax.swing.JComboBox();
        CB_D_M = new javax.swing.JComboBox();
        CB_A_A = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        CB_A_D = new javax.swing.JComboBox();
        CB_A_M = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TF_CTPS = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        CB_T = new javax.swing.JComboBox();
        CB_G = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        CB_F_A = new javax.swing.JComboBox();
        CB_F_D = new javax.swing.JComboBox();
        CB_F_M = new javax.swing.JComboBox();
        CB_I_A = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        CB_I_D = new javax.swing.JComboBox();
        CB_I_M = new javax.swing.JComboBox();
        RB_C = new javax.swing.JRadioButton();
        RB_T = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        jLabel2.setText("jLabel2");

        setTitle("Funcionários Contratados");

        jLabel1.setText("Nome:");

        jLabel3.setText("Cod:");

        TF_Cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CodActionPerformed(evt);
            }
        });

        jLabel4.setText("E-mail:");

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JB_Pesquisar.setText("Pesquisar");
        JB_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_PesquisarActionPerformed(evt);
            }
        });

        JB_Excluir.setText("Excluir");
        JB_Excluir.setEnabled(false);
        JB_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ExcluirActionPerformed(evt);
            }
        });

        JB_Alterar.setText("Alterar");
        JB_Alterar.setEnabled(false);
        JB_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AlterarActionPerformed(evt);
            }
        });

        JB_Cancelar.setText("Cancelar");
        JB_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_CancelarActionPerformed(evt);
            }
        });

        JB_Imprimir.setText("Imprimir");
        JB_Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_ImprimirActionPerformed(evt);
            }
        });

        JP_C.setBorder(javax.swing.BorderFactory.createTitledBorder("Contratado"));

        CB_D_A.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015" }));
        CB_D_A.setEnabled(false);

        CB_D_D.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CB_D_D.setEnabled(false);

        CB_D_M.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        CB_D_M.setEnabled(false);

        CB_A_A.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015" }));

        jLabel7.setText("Demissão:");

        CB_A_D.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CB_A_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_A_DActionPerformed(evt);
            }
        });

        CB_A_M.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        CB_A_M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_A_MActionPerformed(evt);
            }
        });

        jLabel6.setText("Admissão:");

        TF_CTPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_CTPSActionPerformed(evt);
            }
        });

        jLabel5.setText("Nº CTPS:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setText("Titulação:");

        CB_T.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Graduado", "Especialista", "Mestre", "Doutor" }));

        CB_G.setText("Gerente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_T, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CB_G)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CB_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_G))
                .addContainerGap())
        );

        javax.swing.GroupLayout JP_CLayout = new javax.swing.GroupLayout(JP_C);
        JP_C.setLayout(JP_CLayout);
        JP_CLayout.setHorizontalGroup(
            JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_CLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_CLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addGroup(JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JP_CLayout.createSequentialGroup()
                                .addGroup(JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JP_CLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CB_D_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CB_D_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CB_D_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JP_CLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CB_A_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CB_A_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CB_A_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JP_CLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_CTPS, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(JP_CLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        JP_CLayout.setVerticalGroup(
            JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_CLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF_CTPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CB_A_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_A_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_A_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_CLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CB_D_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_D_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_D_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Terceirizado"));

        jLabel9.setText("Inicio de Contrato: ");

        CB_F_A.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015" }));
        CB_F_A.setEnabled(false);

        CB_F_D.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CB_F_D.setEnabled(false);

        CB_F_M.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        CB_F_M.setEnabled(false);

        CB_I_A.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015" }));
        CB_I_A.setEnabled(false);

        jLabel10.setText("Fim de Contrato: ");

        CB_I_D.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        CB_I_D.setEnabled(false);
        CB_I_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_I_DActionPerformed(evt);
            }
        });

        CB_I_M.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        CB_I_M.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CB_F_D, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CB_F_M, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CB_F_A, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CB_I_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CB_I_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CB_I_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CB_I_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_I_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_I_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CB_F_D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_F_M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_F_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup1.add(RB_C);
        RB_C.setSelected(true);
        RB_C.setText("Contratado");
        RB_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_CActionPerformed(evt);
            }
        });

        buttonGroup1.add(RB_T);
        RB_T.setText("Terceirizado");
        RB_T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_TActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(Tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_Email))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TF_Nome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(JB_Pesquisar)
                                        .addGap(18, 18, 18)
                                        .addComponent(JB_Excluir)
                                        .addGap(20, 20, 20)
                                        .addComponent(JB_Alterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(JB_Cancelar)
                                        .addGap(18, 18, 18)
                                        .addComponent(JB_Imprimir))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JP_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RB_C))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(RB_T)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_Cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(TF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TF_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RB_C)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JP_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RB_T)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(JB_Pesquisar)
                    .addComponent(JB_Excluir)
                    .addComponent(JB_Alterar)
                    .addComponent(JB_Cancelar)
                    .addComponent(JB_Imprimir))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_CTPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CTPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CTPSActionPerformed

    private void CB_A_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_A_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_A_DActionPerformed

    private void CB_I_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_I_DActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_I_DActionPerformed

    private void CB_A_MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_A_MActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_A_MActionPerformed

    private void RB_TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_TActionPerformed
       
       Selecionar();        
        
        
        
    }//GEN-LAST:event_RB_TActionPerformed

    private void RB_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_CActionPerformed
       Selecionar();
     
    }//GEN-LAST:event_RB_CActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
         Inserir();
          
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

     public Funcionario existeFuncionario (int codigo)
    {
        for (Funcionario  p : funcionario)
        {
            if (p.getCod() == codigo)
                return p;
        }
        return null;
    }
    
    private void TF_CodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_CodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_CodActionPerformed

    private void JB_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_PesquisarActionPerformed
      
         if (TF_Cod.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Código deve estar preenchido!");
        else
         {
              p = existeFuncionario(Integer.parseInt(TF_Cod.getText()));
              limpar();
              if(p!=null)
              {
                  TF_Cod.setText(p.getCod()+"");
                  TF_Nome.setText(p.getNome());
                  TF_Email.setText(p.getEmail());
                  if(p instanceof Terceirizado)
                  {
                      RB_T.setSelected(true);
                      Selecionar();
                      
                      if(((Terceirizado) p).getInicioC()!=null)
                      {    
                      CB_I_D.setSelectedItem(((Terceirizado) p).getInicioC().get(Calendar.DAY_OF_MONTH)+"");
                      CB_I_M.setSelectedItem(((Terceirizado) p).getInicioC().get(Calendar.MONTH)+"");
                      CB_I_A.setSelectedItem(((Terceirizado) p).getInicioC().get(Calendar.YEAR)+"");
                      }
                      if(((Terceirizado) p).getTerminoC()!=null)
                      {
                      CB_F_D.setSelectedItem(((Terceirizado) p).getTerminoC().get(Calendar.DAY_OF_MONTH)+"");
                      CB_F_M.setSelectedItem(((Terceirizado) p).getTerminoC().get(Calendar.MONTH)+"");
                      CB_F_A.setSelectedItem(((Terceirizado) p).getTerminoC().get(Calendar.YEAR)+"");
                      }
                  }else
                  {
                      RB_C.setSelected(true);
                     Selecionar();
                     TF_CTPS.setText(((Contratado) p).getCtps());
                     
                   
                     
                     
                    if(((Contratado) p).getDataAdm()!=null){
                        
                      
                         
                      CB_A_D.setSelectedItem(((Contratado) p).getDataAdm().get(Calendar.DAY_OF_MONTH)+"");
                      CB_A_M.setSelectedItem(((Contratado) p).getDataAdm().get(Calendar.MONTH)+"");
                      CB_A_A.setSelectedItem(((Contratado) p).getDataAdm().get(Calendar.YEAR)+"");
                     }
                       if(((Contratado) p).getDataDem()!=null){
                      CB_D_D.setSelectedItem(((Contratado) p).getDataDem().get(Calendar.DAY_OF_MONTH)+"");
                      CB_D_M.setSelectedItem(((Contratado) p).getDataDem().get(Calendar.MONTH)+"");
                      CB_D_A.setSelectedItem(((Contratado) p).getDataDem().get(Calendar.YEAR)+"");                    
                       }
                       
                       
                     if(p instanceof Gerente)
                  {
                      
                      CB_G.setSelected(true);
                      CB_T.setSelectedItem(((Gerente) p).getTitulacao());
                  }
                  }
                     JB_Excluir.setEnabled(true);
                JB_Alterar.setEnabled(true);
                  
              }else
             JOptionPane.showMessageDialog(null, "Funcionario não encontrado!");
         
         }
        
        
        
    }//GEN-LAST:event_JB_PesquisarActionPerformed

    private void JB_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ExcluirActionPerformed
       
        
        
        funcionario.remove(p);        
        limpar(); 
    }//GEN-LAST:event_JB_ExcluirActionPerformed

    private void JB_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AlterarActionPerformed
        funcionario.remove(p); 
        Inserir();
        
    }//GEN-LAST:event_JB_AlterarActionPerformed

    private void JB_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_CancelarActionPerformed
       limpar();
    }//GEN-LAST:event_JB_CancelarActionPerformed

    private void JB_ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_ImprimirActionPerformed
        
         DefaultTableModel modelo = (DefaultTableModel)Tabela.getModel();
        String[] linha;
        modelo.setNumRows(0); //Limpa a tabela
        String tipo;
        for (Funcionario p : funcionario){
            if (p instanceof Terceirizado)
                tipo = "Terceirizado";
            else if (p instanceof Gerente)
                tipo = "Gerente";
            else
                tipo = "Contratado";
                        
            linha = new String[]{p.getNome(),tipo};
            modelo.addRow(linha);        
        }
        
        
    }//GEN-LAST:event_JB_ImprimirActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB_A_A;
    private javax.swing.JComboBox CB_A_D;
    private javax.swing.JComboBox CB_A_M;
    private javax.swing.JComboBox CB_D_A;
    private javax.swing.JComboBox CB_D_D;
    private javax.swing.JComboBox CB_D_M;
    private javax.swing.JComboBox CB_F_A;
    private javax.swing.JComboBox CB_F_D;
    private javax.swing.JComboBox CB_F_M;
    private javax.swing.JCheckBox CB_G;
    private javax.swing.JComboBox CB_I_A;
    private javax.swing.JComboBox CB_I_D;
    private javax.swing.JComboBox CB_I_M;
    private javax.swing.JComboBox CB_T;
    private javax.swing.JButton JB_Alterar;
    private javax.swing.JButton JB_Cancelar;
    private javax.swing.JButton JB_Excluir;
    private javax.swing.JButton JB_Imprimir;
    private javax.swing.JButton JB_Pesquisar;
    private javax.swing.JPanel JP_C;
    private javax.swing.JRadioButton RB_C;
    private javax.swing.JRadioButton RB_T;
    private javax.swing.JTextField TF_CTPS;
    private javax.swing.JTextField TF_Cod;
    private javax.swing.JTextField TF_Email;
    private javax.swing.JTextField TF_Nome;
    private javax.swing.JTable Tabela;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void limpar() {
        
        TF_Cod.setText(null);
        TF_Nome.setText(null);
        TF_Email.setText(null);
        TF_CTPS.setText(null);
        CB_A_D.setSelectedIndex(0);
        CB_A_M.setSelectedIndex(0);
        CB_A_A.setSelectedIndex(0);
        CB_D_D.setSelectedIndex(0);
        CB_D_M.setSelectedIndex(0);
        CB_D_A.setSelectedIndex(0);
        CB_G.setSelected(false);
       CB_T.setSelectedIndex(0);
        
         CB_I_D.setSelectedIndex(0);
        CB_I_M.setSelectedIndex(0);
        CB_I_A.setSelectedIndex(0);
        CB_F_D.setSelectedIndex(0);
        CB_F_M.setSelectedIndex(0);
        CB_F_A.setSelectedIndex(0);
        JB_Excluir.setEnabled(false);
                JB_Alterar.setEnabled(false);
        
    }

    private void Selecionar() {
        
         if(RB_T.isSelected())
        {
        
        TF_CTPS.setEnabled(false);
        CB_A_D.setEnabled(false);
         CB_A_M.setEnabled(false);
         CB_A_A.setEnabled(false);
         CB_D_D.setEnabled(false);
                 CB_D_M.setEnabled(false);
                 CB_D_A.setEnabled(false);
         CB_G.setEnabled(false);
         CB_T.setEnabled(false);      
                CB_F_D.setEnabled(true);  
                        CB_F_M.setEnabled(true);
                        CB_F_A.setEnabled(true);
                                CB_I_D.setEnabled(true);
                                CB_I_M.setEnabled(true);
                                        CB_I_A.setEnabled(true);
                                        
                 
        }else
         {
             
            TF_CTPS.setEnabled(true);
        CB_A_D.setEnabled(true);
         CB_A_M.setEnabled(true);
         CB_A_A.setEnabled(true);
         CB_D_D.setEnabled(false);
                 CB_D_M.setEnabled(false);
                 CB_D_A.setEnabled(false);
         CB_G.setEnabled(true);
         CB_T.setEnabled(true);      
                  CB_F_D.setEnabled(false);  
                        CB_F_M.setEnabled(false);
                        CB_F_A.setEnabled(false);
                                CB_I_D.setEnabled(false);
                                CB_I_M.setEnabled(false);
                                        CB_I_A.setEnabled(false);
                 
        }
    }

    private void Inserir() {
        
         if (TF_Cod.getText().equals(""))
          {
              JOptionPane.showMessageDialog(null, "Preencha o campo codigo!");
          }else
          {
              if(existeFuncionario(Integer.parseInt(TF_Cod.getText()))!=null){
              JOptionPane.showMessageDialog(null, "Codigo ja cadastrado!");
              }else
                  {
                  if (TF_Nome.getText().equals(""))
          { 
              JOptionPane.showMessageDialog(null, "Preencha o campo Nome!");
          }else{
                  if(TF_Email.getText().equals(""))
                  {
                     JOptionPane.showMessageDialog(null, "Preencha o campo Email!"); 
                  }else
                  {   
              
               if(RB_C.isSelected())
                    {
                        Calendar c = Calendar.getInstance();
                        c.set(Integer.parseInt(CB_A_A.getSelectedItem().toString()),Integer.parseInt(CB_A_M.getSelectedItem().toString()),
                                Integer.parseInt(CB_A_D.getSelectedItem().toString()));
                        
                                               
                       if(CB_G.isSelected()) 
                     funcionario.add(new Gerente(Integer.parseInt(TF_Cod.getText()), TF_Nome.getText(), TF_Email.getText(), 
                             TF_CTPS.getText(), c , null, CB_T.getSelectedItem().toString()));
                       else
                          funcionario.add(new Contratado(Integer.parseInt(TF_Cod.getText()), TF_Nome.getText(), TF_Email.getText(), 
                             TF_CTPS.getText(), c, null)); 
                    }else
               {
                    Calendar i = Calendar.getInstance();
                    Calendar f = Calendar.getInstance();
                    i.set(Integer.parseInt(CB_I_A.getSelectedItem().toString()),Integer.parseInt(CB_I_M.getSelectedItem().toString()),
                                Integer.parseInt(CB_I_D.getSelectedItem().toString()));
                    f.set(Integer.parseInt(CB_F_A.getSelectedItem().toString()),Integer.parseInt(CB_F_M.getSelectedItem().toString()),
                                Integer.parseInt(CB_F_D.getSelectedItem().toString()));
                   funcionario.add(new Terceirizado(Integer.parseInt(TF_Cod.getText()), TF_Nome.getText(), TF_Email.getText(), 
                             i, f)); 
               }
               
          }
          limpar();
    }
}
     }   }
}
