package GerenciaEmp;

import GerenciaEmp.Classes.Funcionario;
import GerenciaEmp.Classes.Gerente;
import GerenciaEmp.Classes.Material;
import GerenciaEmp.Classes.Contratado;
import GerenciaEmp.Classes.ItemDeMaterial;
import GerenciaEmp.Classes.Terceirizado;
import GerenciaEmp.Classes.Solicitacao;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JFrame;
/**
 *
 * @author Toni
 */
public class MenuPrincipal extends javax.swing.JFrame {

    static public ArrayList<Material> material = new ArrayList();
    static public ArrayList<Funcionario> funcionario = new ArrayList();
    static public ArrayList<Solicitacao> solicitacao = new ArrayList();
    
    static JFrame CadastroMateriais = new JFrame();
    static JFrame CadastroContratado = new JFrame();
    static JFrame Terceirizados = new JFrame();
    static JFrame Contratado_F = new JFrame();
    static JFrame CadastroSolicitacao = new JFrame();
    
    public MenuPrincipal() {
        initComponents();
        
        //Valores inseridos no codigo;
        Calendar c=Calendar.getInstance();
        c.set(2015,10,8);
        funcionario.add(new Gerente(1, "Ana Maria", "asdsadsadsa@","sdsadddsa",c,null,"Mestre")); //get(0)
        funcionario.add(new Terceirizado(2, "Beto Barbosa", "3222-1112@",c,null)); //get(1)
        c.set(2014,6,20);
        funcionario.add(new Terceirizado(22, "Beto Barbosa2", "3222-1112@",c,c)); //get(1)
        c.set(Calendar.DAY_OF_MONTH, 30);
        funcionario.add(new Contratado(3, "Carla Dias", "3223-1ddd@","sdsadsa",c,null)); //get(2)
        
        material.add(new Material(1,"Sem ideia","Caneta", "Mabel",10,"Algma sdsad"));
        material.add(new Material(2,"Sem ideia2","Lápis", "Mabel",15,"gggggd"));
        material.add(new Material(3,"Sem ideia3","Resma de papel A4", "Mabel",16,"Aasdsadssad"));
        
        ArrayList <ItemDeMaterial> itens = new ArrayList();
        c=Calendar.getInstance();
        c.set(2012,5,10);
        itens.add(new ItemDeMaterial(5,material.get(0)));
        itens.add(new ItemDeMaterial(6,material.get(1)));
        itens.add(new ItemDeMaterial(2,material.get(2)));
        solicitacao.add(new Solicitacao(1,c,funcionario.get(0),itens));
        itens.clear();
        
        c=Calendar.getInstance();
        c.set(2013,7,22);
        itens.add(new ItemDeMaterial(6,material.get(0)));
        itens.add(new ItemDeMaterial(4,material.get(1)));
        itens.add(new ItemDeMaterial(3,material.get(2)));
        solicitacao.add(new Solicitacao(2,c,funcionario.get(1),itens));
        itens.clear();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        idmRelSolicitacoes = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Funcionários");

        jMenu1.setText("Cadastro");

        jMenuItem5.setText("Funcionarios");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setText("Materiais");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Solicitação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatório");

        jMenu4.setText("Funcionarios");

        jMenuItem6.setText("Terceirizados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Contratados");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenu2.add(jMenu4);

        jMenuItem8.setText("Materiais");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        idmRelSolicitacoes.setText("Solicitações");
        idmRelSolicitacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idmRelSolicitacoesActionPerformed(evt);
            }
        });
        jMenu2.add(idmRelSolicitacoes);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Terceirizados rT = null;
        if(rT==null)
            rT = new Terceirizados();
        rT.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CadastroContratado cC = null;
        if(cC==null)
            cC = new CadastroContratado();
        cC.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CadastroMaterial cM = null;
        if(cM==null)
            cM = new CadastroMaterial();
        cM.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        Contratado_F cF = null;
        if(cF==null)
            cF = new Contratado_F();
        cF.setVisible(true);     
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
         RelatorioMaterial m = null;
        if(m==null)
            m = new  RelatorioMaterial();
        m.setVisible(true);
        
          
    
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastroSolicitacao c = null;
        if(c== null)
            c = new CadastroSolicitacao();
        c.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void idmRelSolicitacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idmRelSolicitacoesActionPerformed
        RelatorioSolicitacao rs = null;
        if(rs==null)
            rs = new RelatorioSolicitacao();
        rs.setVisible(true);
    }//GEN-LAST:event_idmRelSolicitacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem idmRelSolicitacoes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    // End of variables declaration//GEN-END:variables
}
