package GerenciaEmp;
import GerenciaEmp.Classes.Funcionario;
import GerenciaEmp.Classes.Solicitacao;
import static GerenciaEmp.MenuPrincipal.funcionario;
import static GerenciaEmp.MenuPrincipal.solicitacao;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;
public class RelatorioSolicitacao extends javax.swing.JFrame {

/**
 *
 * @author Toni
 */
    public RelatorioSolicitacao() {
        initComponents();
        
      

            
        
        
        
        for (Funcionario f : funcionario) {
            cbxFuncionarios.addItem(f.getNome());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSolicitacoes = new javax.swing.JTable();
        rdbTodos = new javax.swing.JRadioButton();
        rdbPeriodo = new javax.swing.JRadioButton();
        rdbFuncionario = new javax.swing.JRadioButton();
        cbxDeDia = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        cbxDeMes = new javax.swing.JComboBox();
        cbxDeAno = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbxAteDia = new javax.swing.JComboBox();
        cbxAteMes = new javax.swing.JComboBox();
        cbxAteAno = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbxFuncionarios = new javax.swing.JComboBox();
        btnImprimir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFrame2.setVisible(true);

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblSolicitacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Data", "Funcionario", "Quant de Itens"
            }
        ));
        tblSolicitacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSolicitacoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSolicitacoes);

        buttonGroup1.add(rdbTodos);
        rdbTodos.setSelected(true);
        rdbTodos.setText("Todos");
        rdbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTodosActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbPeriodo);
        rdbPeriodo.setText("Período");
        rdbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPeriodoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbFuncionario);
        rdbFuncionario.setText("Funcionário");
        rdbFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbFuncionarioActionPerformed(evt);
            }
        });

        cbxDeDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxDeDia.setEnabled(false);

        jLabel1.setText("De:");

        cbxDeMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxDeMes.setEnabled(false);

        cbxDeAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015" }));
        cbxDeAno.setEnabled(false);

        jLabel2.setText("Até:");

        cbxAteDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbxAteDia.setEnabled(false);

        cbxAteMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbxAteMes.setEnabled(false);

        cbxAteAno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015" }));
        cbxAteAno.setEnabled(false);

        jLabel3.setText("Solicitado por:");

        cbxFuncionarios.setEnabled(false);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDeDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDeMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxDeAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxAteDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdbTodos)
                                .addGap(18, 18, 18)
                                .addComponent(rdbPeriodo)
                                .addGap(18, 18, 18)
                                .addComponent(rdbFuncionario))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxAteMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxAteAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbTodos)
                    .addComponent(rdbPeriodo)
                    .addComponent(rdbFuncionario)
                    .addComponent(btnImprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxDeDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cbxDeMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxDeAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAteDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAteMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAteAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSolicitacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSolicitacoesMouseClicked
        Solicitacao s = new Solicitacao();
        s = solicitacao.get(tblSolicitacoes.getSelectedRow());
        s.printIntens();
    }//GEN-LAST:event_tblSolicitacoesMouseClicked

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        if(rdbTodos.isSelected()){
            DefaultTableModel modelo = (DefaultTableModel) tblSolicitacoes.getModel();
            String[] linha;
            modelo.setNumRows(0);
            for (Solicitacao x : solicitacao) {
                linha = new String[]{x.getCod() + "", x.getData().get(Calendar.DAY_OF_MONTH) + "/" + x.getData().get(Calendar.MONTH) + "/" + x.getData().get(Calendar.YEAR), x.getF().getNome(), x.getQuantItens() + ""};
                modelo.addRow(linha);
            }
        }
        if(rdbPeriodo.isSelected()){
            Calendar de = Calendar.getInstance();
            de.set(Calendar.DAY_OF_MONTH,Integer.parseInt(cbxDeDia.getSelectedItem().toString()));
            de.set(Calendar.MONTH,Integer.parseInt(cbxDeMes.getSelectedItem().toString()));
            de.set(Calendar.YEAR,Integer.parseInt(cbxDeAno.getSelectedItem().toString()));
            
            Calendar ate = Calendar.getInstance();
            ate.set(Calendar.DAY_OF_MONTH, Integer.parseInt(cbxAteDia.getSelectedItem().toString()));
            ate.set(Calendar.MONTH, Integer.parseInt(cbxAteMes.getSelectedItem().toString()));
            ate.set(Calendar.YEAR, Integer.parseInt(cbxAteAno.getSelectedItem().toString()));
            
            
            DefaultTableModel modelo = (DefaultTableModel) tblSolicitacoes.getModel();
            String[] linha;
            modelo.setNumRows(0);
            for (Solicitacao x : solicitacao) {
                
                if(x.getData().after(de) && x.getData().before(ate)){
                    linha = new String[]{x.getCod() + "", x.getData().get(Calendar.DAY_OF_MONTH) + "/" + x.getData().get(Calendar.MONTH) + "/" + x.getData().get(Calendar.YEAR), x.getF().getNome(), x.getQuantItens() + ""};
                    modelo.addRow(linha);
                }
            } 
        }
        if(rdbFuncionario.isSelected()){
            DefaultTableModel modelo = (DefaultTableModel) tblSolicitacoes.getModel();
            String[] linha;
            modelo.setNumRows(0);
            for (Solicitacao x : solicitacao) {
                if (x.getF()==funcionario.get(cbxFuncionarios.getSelectedIndex())) {
                    linha = new String[]{x.getCod() + "", x.getData().get(Calendar.DAY_OF_MONTH) + "/" + x.getData().get(Calendar.MONTH) + "/" + x.getData().get(Calendar.YEAR), x.getF().getNome(), x.getQuantItens() + ""};
                    modelo.addRow(linha);
                }
            }
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblSolicitacoes.getModel();
        String[] linha;
        modelo.setNumRows(0);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void rdbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPeriodoActionPerformed
        enableData();
        disableFunc();
    }//GEN-LAST:event_rdbPeriodoActionPerformed

    private void rdbFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbFuncionarioActionPerformed
        enableFunc();
        disabeData();
    }//GEN-LAST:event_rdbFuncionarioActionPerformed

    private void rdbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTodosActionPerformed
        disabeData();
        disableFunc();
    }//GEN-LAST:event_rdbTodosActionPerformed

    public void enableData(){
        cbxDeDia.setEnabled(true);
        cbxDeMes.setEnabled(true);
        cbxDeAno.setEnabled(true);
        cbxAteDia.setEnabled(true);
        cbxAteMes.setEnabled(true);
        cbxAteAno.setEnabled(true);
    }
    
    public void disabeData(){
        cbxDeDia.setEnabled(false);
        cbxDeMes.setEnabled(false);
        cbxDeAno.setEnabled(false);
        cbxAteDia.setEnabled(false);
        cbxAteMes.setEnabled(false);
        cbxAteAno.setEnabled(false);        
    }
    
    public void enableFunc(){
        cbxFuncionarios.setEnabled(true);
    }
    
    public void disableFunc(){
        cbxFuncionarios.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbxAteAno;
    private javax.swing.JComboBox cbxAteDia;
    private javax.swing.JComboBox cbxAteMes;
    private javax.swing.JComboBox cbxDeAno;
    private javax.swing.JComboBox cbxDeDia;
    private javax.swing.JComboBox cbxDeMes;
    private javax.swing.JComboBox cbxFuncionarios;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbFuncionario;
    private javax.swing.JRadioButton rdbPeriodo;
    private javax.swing.JRadioButton rdbTodos;
    private javax.swing.JTable tblSolicitacoes;
    // End of variables declaration//GEN-END:variables
}
