/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GerenciaEmp;

import GerenciaEmp.Classes.Funcionario;
import GerenciaEmp.Classes.Gerente;
import GerenciaEmp.Classes.Terceirizado;
import static GerenciaEmp.MenuPrincipal.funcionario;
import java.util.Calendar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Toni C
 */
public class Terceirizados extends javax.swing.JFrame {

         
    /**
     * Creates new form Terceirizados
     */
    public Terceirizados() {
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel)Tabela1.getModel();
        String[] linha;
        modelo.setNumRows(0); //Limpa a tabela
        String tipo="-",tipo2="-";
       
          
            
        for (Funcionario p : funcionario){
            if (p instanceof Terceirizado)
                {   
                    if(((Terceirizado) p).getInicioC()!=null)
                    {
                        tipo=((Terceirizado) p).getInicioC().get(Calendar.DAY_OF_MONTH)+"/"+
                               ((Terceirizado) p).getInicioC().get(Calendar.MONTH)+"/"+
                               ((Terceirizado) p).getInicioC().get(Calendar.YEAR) ;
                    }
                        if(((Terceirizado) p).getTerminoC()!=null)
                        {
                                tipo2=((Terceirizado) p).getTerminoC().get(Calendar.DAY_OF_MONTH)+"/"+
                               ((Terceirizado) p).getTerminoC().get(Calendar.MONTH)+"/"+
                               ((Terceirizado) p).getTerminoC().get(Calendar.YEAR) ;
                        }
                  
                linha = new String[]{p.getCod()+"",p.getNome(),tipo, tipo2};
                
                modelo.addRow(linha);  
                }
            
            tipo="-";
            tipo2="-";
            }
                  
        
        
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela1 = new javax.swing.JTable();

        Tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Data de Inicio", "Fim de Contrato"
            }
        ));
        jScrollPane1.setViewportView(Tabela1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
